version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
      - image: circleci/mysql:5.7
        command: service mysql start
        environment:
          MYSQL_DATABASE: sbjauth
          MYSQL_USER: root 
          MYSQL_ROOT_HOST: %
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: /tmp/cc2
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run:
          name: Install Gradle
          command: |
            add-apt-repository -y ppa:cwchien/gradle
            apt-get -yqq update
            apt-get -yqq install gradle
            ln -s /usr/lib/jvm/java-8-oracle /usr/lib/jvm/default-java
            gradle -v
      - run: gradle -q wrap
      - run: ./gradlew -q dependencies
      - run: apt-get -yqq install mysql-client
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: mysql -u root -e 'show tables;'
      - run: ./gradlew test
