version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
        environment:
          MYSQL_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        command: [--character-set-server=utf8, --collation-server=utf8_general_ci, --default-storage-engine=innodb]
        environment:
          MYSQL_DATABASE: sbjauth
          MYSQL_USER: root
          MYSQL_ROOT_HOST: '%'
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: /tmp/cc2
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - run: echo $MYSQL_HOST
      - run: apt-get -yqq update
      - run: apt-get -yqq install mysql-client
      - run:
          name: install dockerize
          command: |
            wget -q https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            sudo tar -C /usr/local/bin -xzf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            dockerize -version
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: mysql -u root -e 'show tables;'
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run:
          name: Install Gradle
          command: |
            add-apt-repository -y ppa:cwchien/gradle
            apt-get -yqq install gradle
            ln -s /usr/lib/jvm/java-8-oracle /usr/lib/jvm/default-java
            gradle -v
      - run: gradle -q wrap
      - run: ./gradlew -q dependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test
