version: 2
jobs:
  build:
    docker:
      - image: circleci/jdk8:0.1.1
      - image: circleci/mysql:5.7
    working_directory: /tmp/cc2
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run:
          name: Install Gradle
          command: |
            add-apt-repository -y ppa:cwchien/gradle
            apt-get -yqq update
            apt-get -yqq install gradle
            ln -s /usr/lib/jvm/java-8-oracle /usr/lib/jvm/default-java
            gradle --version
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
